/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initTracing(): void
export declare class ChiaBlockListener {
  constructor()
  addPeer(host: string, port: number, networkId: string): number
  disconnectPeer(peerId: number): boolean
  disconnectAllPeers(): void
  getConnectedPeers(): Array<number>
  on(event: string, callback: (...args: any[]) => any): void
  off(event: string, callback: (...args: any[]) => any): void
  getBlockByHeight(peerId: number, height: number): object
  getBlocksRange(peerId: number, startHeight: number, endHeight: number): Array<object>
  processTransactionGenerator(generatorHex: string): object
}
